import { scenarioInventory as ids } from "./scenario-inventory.js";
import type { ThemeColorScenario } from "./types.js";

const desktop = { width: 1440, height: 1000 } as const;
const mobile = { width: 390, height: 844 } as const;
const themes = ["light", "dark"] as const;

const allThemeColorScenarios = [
  {
    scenarioId: "workspace-overview",
    route: "/workspaces",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Workspaces Overview" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: [...ids["workspace-overview"], ...ids["global-css"]],
  },
  {
    scenarioId: "workspace-empty",
    route: "/workspaces",
    fixtureProfile: "workspace-empty",
    state: "normal",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Workspaces Overview" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-overview"],
  },
  {
    scenarioId: "workspace-new-hover",
    route: "/workspaces",
    fixtureProfile: "demo",
    state: "hover",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "button", name: "New workspace" },
    actions: [{ kind: "hover", role: "button", name: "New workspace" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-overview"],
  },
  {
    scenarioId: "workspace-danger-hover",
    route: "/workspaces",
    fixtureProfile: "demo",
    state: "hover",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "button", name: "Purge files" },
    actions: [{ kind: "hover", role: "button", name: "Purge files" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["global-css"],
  },
  {
    scenarioId: "workspace-config-dialog",
    route: "/workspaces",
    fixtureProfile: "demo",
    state: "dialog-overlay",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Workspace Settings" },
    actions: [
      { kind: "click", role: "button", name: "Configure this workspace" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-config-dialog"],
  },
  {
    scenarioId: "workspace-template-review",
    route: "/workspaces",
    fixtureProfile: "workspace-upgrade",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Workspace Settings" },
    actions: [
      { kind: "click", role: "button", name: "Configure this workspace" },
      { kind: "click", role: "button", name: "Template" },
      { kind: "wait", milliseconds: 500 },
      { kind: "click", role: "radio", name: "Keep workspace" },
      { kind: "wait", milliseconds: 200 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-config-dialog"],
  },
  {
    scenarioId: "workspace-absorb-review",
    route: "/workspaces",
    fixtureProfile: "demo",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Workspace Settings" },
    actions: [
      { kind: "click", role: "button", name: "Configure this workspace" },
      { kind: "click", role: "button", name: "Consolidate" },
      { kind: "select", index: 0, value: "demo-ws" },
      { kind: "wait", milliseconds: 500 },
      { kind: "click", role: "radio", name: "Use source" },
      { kind: "wait", milliseconds: 200 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-config-dialog"],
  },
  {
    scenarioId: "workspace-template-blocked",
    route: "/workspaces",
    fixtureProfile: "workspace-upgrade-blocked",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Workspace Settings" },
    actions: [
      { kind: "click", role: "button", name: "Configure this workspace" },
      { kind: "click", role: "button", name: "Template" },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-config-dialog"],
  },
  {
    scenarioId: "workspace-absorb-blocked",
    route: "/workspaces",
    fixtureProfile: "workspace-absorb-blocked",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Workspace Settings" },
    actions: [
      { kind: "click", role: "button", name: "Configure this workspace" },
      { kind: "click", role: "button", name: "Consolidate" },
      { kind: "select", index: 0, value: "demo-ws" },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-config-dialog"],
  },
  {
    scenarioId: "workspace-config-stale-test",
    route: "/workspaces",
    fixtureProfile: "workspace-config-stale",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Workspace Settings" },
    actions: [
      { kind: "click", role: "button", name: "Configure this workspace" },
      { kind: "click", role: "button", name: "AI Provider" },
      { kind: "wait", milliseconds: 1_000 },
      { kind: "fill", placeholder: "sk-...", value: "audit-key-before-test" },
      { kind: "wait", milliseconds: 300 },
      { kind: "click", role: "button", name: "Test" },
      { kind: "wait", milliseconds: 500 },
      { kind: "fill", placeholder: "sk-...", value: "audit-key-after-test" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-config-dialog"],
  },
  {
    scenarioId: "workspace-mobile",
    route: "/workspaces",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: mobile,
    ready: { role: "heading", name: "Workspaces Overview" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-mobile"],
  },
  {
    scenarioId: "workspace-resume",
    route: "/workspaces/demo-ws",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "button", name: "Open c1" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-empty-pane",
    route: "/workspaces/demo-ws",
    fixtureProfile: "workspace-resume",
    state: "normal",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "button", name: "+ Start a new session" },
    actions: [{ kind: "wait", milliseconds: 500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-paused",
    route: "/workspaces/demo-ws",
    fixtureProfile: "workspace-resume",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "button", name: "Resume p-audit" },
    actions: [{ kind: "click", role: "button", name: "Resume p-audit" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-paused-visible",
    route: "/workspaces/demo-ws/s/audit-pi-session",
    fixtureProfile: "workspace-resume",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [{ kind: "wait", milliseconds: 500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-webpi",
    route: "/workspaces/demo-ws",
    fixtureProfile: "workspace-webpi",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "button", name: "Retry" },
    actions: [{ kind: "click", role: "button", name: "Open p-audit" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-webpi-collapsed",
    route: "/workspaces/demo-ws",
    fixtureProfile: "workspace-webpi",
    state: "normal",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "button", name: "Retry" },
    actions: [
      { kind: "click", role: "button", name: "Open p-audit" },
      { kind: "wait", milliseconds: 500 },
      { kind: "click-css", selector: ".webpi-activity > summary", text: "" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-webpi-complete",
    route: "/workspaces/demo-ws",
    fixtureProfile: "workspace-webpi-complete",
    state: "normal",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [
      { kind: "click", role: "button", name: "Open p-audit" },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-webpi-running",
    route: "/workspaces/demo-ws",
    fixtureProfile: "workspace-webpi-running",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [
      { kind: "click", role: "button", name: "Open p-audit" },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-html-report",
    route: "/workspaces/demo-ws",
    fixtureProfile: "demo",
    state: "normal",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [
      { kind: "click", role: "button", name: "Files" },
      { kind: "wait", milliseconds: 300 },
      { kind: "click-css", selector: ".files-row", text: "audit-report.html" },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-narrow-files",
    route: "/workspaces/demo-ws",
    fixtureProfile: "demo",
    state: "normal",
    stateDriver: "action",
    themes,
    viewport: { width: 850, height: 900 },
    ready: { role: "button", name: "Files" },
    actions: [
      { kind: "click", role: "button", name: "Files" },
      { kind: "wait", milliseconds: 300 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-terminal-connected",
    route: "/workspaces/demo-ws",
    fixtureProfile: "terminal-connected",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [{ kind: "click", role: "button", name: "Continue" }],
    expectedSurface: "typed-non-dom",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-terminal-connecting",
    route: "/workspaces/demo-ws",
    fixtureProfile: "terminal-connecting",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [{ kind: "click", role: "button", name: "Continue" }],
    expectedSurface: "typed-non-dom",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-terminal-reconnecting",
    route: "/workspaces/demo-ws",
    fixtureProfile: "terminal-reconnecting",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [{ kind: "click", role: "button", name: "Continue" }],
    expectedSurface: "typed-non-dom",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-terminal-kicked",
    route: "/workspaces/demo-ws",
    fixtureProfile: "terminal-kicked",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [{ kind: "click", role: "button", name: "Continue" }],
    expectedSurface: "typed-non-dom",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-terminal-locked",
    route: "/workspaces/demo-ws",
    fixtureProfile: "terminal-locked",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [{ kind: "click", role: "button", name: "Continue" }],
    expectedSurface: "typed-non-dom",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "workspace-terminal-closed",
    route: "/workspaces/demo-ws",
    fixtureProfile: "terminal-closed",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [{ kind: "click", role: "button", name: "Continue" }],
    expectedSurface: "typed-non-dom",
    inventoryIds: ids["workspace-terminal"],
  },
  {
    scenarioId: "first-run",
    route: "/onboarding",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["first-run"],
  },
  {
    scenarioId: "first-run-incomplete",
    route: "/onboarding",
    fixtureProfile: "first-run-incomplete",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["first-run"],
  },
  {
    scenarioId: "first-run-trading-locked",
    route: "/onboarding?onboardingStep=broker",
    fixtureProfile: "first-run-locked",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [
      { kind: "wait", milliseconds: 1_000 },
      { kind: "click", role: "button", name: "Continue" },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["first-run"],
  },
  {
    scenarioId: "first-run-finish",
    route: "/onboarding?onboardingStep=broker",
    fixtureProfile: "first-run-locked",
    state: "normal",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [
      { kind: "wait", milliseconds: 1_000 },
      { kind: "click", role: "button", name: "Continue" },
      { kind: "wait", milliseconds: 300 },
      { kind: "click", role: "button", name: "Continue with Readonly" },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: [...ids["first-run"], ...ids["global-css"]],
  },
  {
    scenarioId: "first-run-uta-escape-disabled",
    route: "/onboarding?onboardingStep=broker",
    fixtureProfile: "first-run-no-uta",
    state: "disabled",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [
      { kind: "wait", milliseconds: 1_000 },
      { kind: "click", role: "button", name: "Continue" },
      { kind: "wait", milliseconds: 300 },
      { kind: "click", role: "button", name: "Connect broker account" },
      { kind: "wait", milliseconds: 300 },
      {
        kind: "click-css",
        selector: ".oa-dialog-surface button",
        text: "Continue in research-only mode",
      },
      { kind: "hover-css", selector: ".oa-dialog-surface button:disabled" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: [...ids["first-run"], ...ids["create-uta-dialog"]],
  },
  {
    scenarioId: "workspace-manager",
    route: "/chat/manager",
    fixtureProfile: "demo",
    state: "normal",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Manage the floor, not another desk." },
    actions: [{ kind: "wait", milliseconds: 500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-overview"],
  },
  {
    scenarioId: "workspace-manager-no-creds",
    route: "/chat/manager",
    fixtureProfile: "chat-no-creds",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Manage the floor, not another desk." },
    actions: [{ kind: "wait", milliseconds: 500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-overview"],
  },
  {
    scenarioId: "workspace-manager-no-creds-hover",
    route: "/chat/manager",
    fixtureProfile: "chat-no-creds",
    state: "hover",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Manage the floor, not another desk." },
    actions: [
      { kind: "hover", role: "button", name: "Configure an AI provider" },
      { kind: "wait", milliseconds: 200 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["workspace-overview"],
  },
  {
    scenarioId: "chat",
    route: "/chat",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "What do you want to look into?" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["chat"],
  },
  {
    scenarioId: "chat-mobile",
    route: "/chat",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: mobile,
    ready: { role: "heading", name: "What do you want to look into?" },
    actions: [{ kind: "click", role: "button", name: "Open menu" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["chat"],
  },
  {
    scenarioId: "chat-no-agents",
    route: "/chat",
    fixtureProfile: "chat-no-agents",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "What do you want to look into?" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["chat"],
  },
  {
    scenarioId: "chat-selected-missing",
    route: "/chat",
    fixtureProfile: "chat-selected-missing",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "What do you want to look into?" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["chat"],
  },
  {
    scenarioId: "chat-no-creds",
    route: "/chat",
    fixtureProfile: "chat-no-creds",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "What do you want to look into?" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["chat"],
  },
  {
    scenarioId: "chat-no-creds-hover",
    route: "/chat",
    fixtureProfile: "chat-no-creds",
    state: "hover",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "What do you want to look into?" },
    actions: [
      { kind: "hover", role: "button", name: "Configure an AI provider" },
      { kind: "wait", milliseconds: 300 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["chat"],
  },
  {
    scenarioId: "automation-runs",
    route: "/automation/runs",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Runs" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["automation-runs"],
  },
  {
    scenarioId: "automation-loading",
    route: "/automation/runs",
    fixtureProfile: "automation-loading",
    state: "normal",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Runs" },
    actions: [],
    expectedSurface: "dom-or-css",
    collectBeforeNetworkIdle: true,
    inventoryIds: [...ids["automation-runs"], ...ids["global-css"]],
  },
  {
    scenarioId: "automation-run-expanded",
    route: "/automation/runs",
    fixtureProfile: "demo",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Runs" },
    actions: [
      {
        kind: "click",
        role: "button",
        name: "Compute a quant snapshot",
        exact: false,
      },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["automation-runs"],
  },
  {
    scenarioId: "automation-run-open-hover",
    route: "/automation/runs",
    fixtureProfile: "demo",
    state: "hover",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Runs" },
    actions: [
      {
        kind: "click",
        role: "button",
        name: "Compute a quant snapshot",
        exact: false,
      },
      { kind: "hover", role: "button", name: "Open as session" },
      { kind: "wait", milliseconds: 300 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["automation-runs"],
  },
  {
    scenarioId: "automation-run-failed",
    route: "/automation/runs",
    fixtureProfile: "automation-run-failed",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Runs" },
    actions: [
      {
        kind: "click",
        role: "button",
        name: "Audit failed automation output",
        exact: false,
      },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["automation-runs"],
  },
  {
    scenarioId: "automation-output-error",
    route: "/automation/runs",
    fixtureProfile: "automation-output-error",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Runs" },
    actions: [
      {
        kind: "click",
        role: "button",
        name: "Compute a quant snapshot",
        exact: false,
      },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["automation-runs"],
  },
  {
    scenarioId: "automation-refresh-error",
    route: "/automation/runs",
    fixtureProfile: "automation-refresh-error",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Runs" },
    actions: [{ kind: "wait", milliseconds: 4_500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["automation-runs"],
  },
  {
    scenarioId: "automation-list-error",
    route: "/automation/runs",
    fixtureProfile: "automation-list-error",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Runs" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["automation-runs"],
  },
  {
    scenarioId: "automation-api",
    route: "/automation/api",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Workspace automation" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["automation-api"],
  },
  {
    scenarioId: "issues-due",
    route: "/issues",
    fixtureProfile: "issues-due",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Issues" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issues-board"],
  },
  {
    scenarioId: "issues-board",
    route: "/issues",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Issues" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issues-board"],
  },
  {
    scenarioId: "issues-invalid",
    route: "/issues",
    fixtureProfile: "issues-invalid",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Issues" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issues-board"],
  },
  {
    scenarioId: "issues-error",
    route: "/issues",
    fixtureProfile: "issues-error",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Issues" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issues-board"],
  },
  {
    scenarioId: "issues-stale",
    route: "/issues",
    fixtureProfile: "issues-stale",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Issues" },
    actions: [{ kind: "wait", milliseconds: 15_500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issues-board"],
  },
  {
    scenarioId: "issues-failed-health",
    route: "/issues",
    fixtureProfile: "issues-failed-health",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Issues" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issues-board"],
  },
  {
    scenarioId: "issue-status-variants",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-status-variants",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-detail",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-inquiry-variants",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "inquiry-variants",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-inquiry-error",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "inquiry-error",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-comment-focus",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "demo",
    state: "focus",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "textbox", name: "Leave a comment…" },
    actions: [{ kind: "focus", role: "textbox", name: "Leave a comment…" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-what-focus",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "demo",
    state: "focus",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [
      { kind: "wait", milliseconds: 1_500 },
      { kind: "focus-css", selector: '[aria-label="Issue What"]' },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: [...ids["issue-detail"], ...ids["global-css"]],
  },
  {
    scenarioId: "issue-what-save-error",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-property-error",
    state: "error",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [
      { kind: "wait", milliseconds: 1_500 },
      {
        kind: "fill-css",
        selector: '[aria-label="Issue What"]',
        value: "Audit save failure",
      },
      { kind: "wait", milliseconds: 1_200 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-what-node-selection",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-node-selection",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [
      { kind: "wait", milliseconds: 1_500 },
      { kind: "click-css", selector: ".what-editor-content hr", text: "" },
      { kind: "wait", milliseconds: 200 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: [...ids["issue-detail"], ...ids["global-css"]],
  },
  {
    scenarioId: "issue-comment-error",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-comment-error",
    state: "error",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "textbox", name: "Leave a comment…" },
    actions: [
      {
        kind: "fill",
        placeholder: "Leave a comment…",
        value: "audit comment failure",
      },
      { kind: "click", role: "button", name: "Comment" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-property-error",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-property-error",
    state: "error",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [{ kind: "select", index: 0, value: "done" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-continue-error",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-continue-error",
    state: "error",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [{ kind: "click", role: "button", name: "Continue" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-detail-load-error",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-detail-load-error",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "button", name: "Issues", exact: true },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-agent-credential-missing",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-credential-missing",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-runtime-failures",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-runtime-failures",
    state: "error",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [
      { kind: "hover", role: "button", name: "Retry now" },
      { kind: "wait", milliseconds: 300 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-runtime-failures-base",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-runtime-failures",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "issue-delivery-failed",
    route: "/issues/demo-ws-auto-quant/morning-scan",
    fixtureProfile: "issue-delivery-failed",
    state: "error",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Morning movers scan" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["issue-detail"],
  },
  {
    scenarioId: "trading-as-git",
    route: "/trading-as-git",
    fixtureProfile: "trading-approval",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Trading as Git" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["trading-as-git"],
  },
  {
    scenarioId: "trading-as-git-submitted",
    route: "/trading-as-git",
    fixtureProfile: "trading-approval",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Trading as Git" },
    actions: [
      {
        kind: "click",
        role: "button",
        name: "Submitted broker order",
        exact: false,
      },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["trading-as-git"],
  },
  {
    scenarioId: "trading-as-git-rejected",
    route: "/trading-as-git",
    fixtureProfile: "trading-approval",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Trading as Git" },
    actions: [
      {
        kind: "click",
        role: "button",
        name: "User rejected broker order",
        exact: false,
      },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["trading-as-git"],
  },
  {
    scenarioId: "trading-as-git-staged",
    route: "/trading-as-git",
    fixtureProfile: "trading-approval",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Trading as Git" },
    actions: [
      {
        kind: "click",
        role: "button",
        name: "Staged operations",
        exact: false,
      },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["trading-as-git"],
  },
  {
    scenarioId: "market-search-main-variants",
    route: "/market",
    fixtureProfile: "market-search-variants",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [
      {
        kind: "fill-css",
        selector:
          'main input[placeholder="Search assets — AAPL, bitcoin, EUR, gold…"]',
        value: "audit",
      },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["market-detail"],
  },
  {
    scenarioId: "market-search-sidebar-variants",
    route: "/market/equity/AAPL",
    fixtureProfile: "market-search-variants",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "AAPL" },
    actions: [
      { kind: "fill-css", selector: "aside input", value: "audit" },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["market-detail"],
  },
  {
    scenarioId: "market-detail",
    route: "/market/equity/AAPL",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "AAPL" },
    actions: [],
    expectedSurface: "typed-non-dom",
    inventoryIds: ids["market-detail"],
  },
  {
    scenarioId: "market-detail-pinned",
    route: "/market/equity/AAPL",
    fixtureProfile: "demo",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "AAPL" },
    actions: [
      { kind: "click", role: "button", name: "Pin" },
      { kind: "hover-css", selector: "h1" },
      { kind: "wait", milliseconds: 300 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["market-detail"],
  },
  {
    scenarioId: "market-detail-pinned-hover",
    route: "/market/equity/AAPL",
    fixtureProfile: "demo",
    state: "hover",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "AAPL" },
    actions: [
      { kind: "click", role: "button", name: "Pin" },
      { kind: "hover", role: "button", name: "Pinned" },
      { kind: "wait", milliseconds: 300 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["market-detail"],
  },
  {
    scenarioId: "market-board",
    route: "/market/boards/movers",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["market-board"],
  },
  {
    scenarioId: "market-stale",
    route: "/market/boards/movers",
    fixtureProfile: "market-stale",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["market-board"],
  },
  {
    scenarioId: "market-term-structure",
    route: "/market/boards/term-structure",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [],
    expectedSurface: "typed-non-dom",
    inventoryIds: ids["market-board"],
  },
  {
    scenarioId: "market-shipping",
    route: "/market/boards/shipping",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [],
    expectedSurface: "typed-non-dom",
    inventoryIds: ids["market-board"],
  },
  {
    scenarioId: "market-rotation",
    route: "/market/rotation",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["market-rotation"],
  },
  {
    scenarioId: "connector-status",
    route: "/connectors",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["connector-status"],
  },
  {
    scenarioId: "connector-status-hover",
    route: "/connectors",
    fixtureProfile: "demo",
    state: "hover",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [{ kind: "hover-css", selector: ".oa-pressable" }],
    expectedSurface: "dom-or-css",
    inventoryIds: [...ids["connector-status"], ...ids["global-css"]],
  },
  {
    scenarioId: "connector-status-starting",
    route: "/connectors",
    fixtureProfile: "connector-starting",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["connector-status"],
  },
  {
    scenarioId: "connector-status-awaiting",
    route: "/connectors",
    fixtureProfile: "connector-awaiting-status",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["connector-status"],
  },
  {
    scenarioId: "connector-status-ready",
    route: "/connectors",
    fixtureProfile: "connector-ready",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["connector-status"],
  },
  {
    scenarioId: "connector-status-needs-setup",
    route: "/connectors",
    fixtureProfile: "connector-needs-setup",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["connector-status"],
  },
  {
    scenarioId: "connector-settings",
    route: "/settings/connectors",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["connector-settings"],
  },
  {
    scenarioId: "connector-settings-starting",
    route: "/settings/connectors",
    fixtureProfile: "connector-starting",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["connector-settings"],
  },
  {
    scenarioId: "connector-settings-awaiting",
    route: "/settings/connectors",
    fixtureProfile: "connector-awaiting",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["connector-settings"],
  },
  {
    scenarioId: "connector-settings-ready",
    route: "/settings/connectors",
    fixtureProfile: "connector-ready",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connectors" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["connector-settings"],
  },
  {
    scenarioId: "ai-credential-dialog",
    route: "/settings/ai-provider",
    fixtureProfile: "credential-test",
    state: "dialog-overlay",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Add credential" },
    actions: [{ kind: "click", role: "button", name: "+ Add" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["ai-credential-dialog"],
  },
  {
    scenarioId: "ai-credential-stale-test",
    route: "/settings/ai-provider",
    fixtureProfile: "credential-test",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Add credential" },
    actions: [
      { kind: "click", role: "button", name: "+ Add" },
      { kind: "click", role: "button", name: "Audit OpenAI", exact: false },
      {
        kind: "fill",
        placeholder: "Enter API key",
        value: "audit-key-before-test",
      },
      {
        kind: "fill",
        placeholder: "Exact provider model ID",
        value: "gpt-audit",
      },
      { kind: "click", role: "button", name: "Test connection" },
      {
        kind: "fill",
        placeholder: "Enter API key",
        value: "audit-key-after-test",
      },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["ai-credential-dialog"],
  },
  {
    scenarioId: "inbox",
    route: "/inbox",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Inbox" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["inbox"],
  },
  {
    scenarioId: "inbox-time-read",
    route: "/inbox",
    fixtureProfile: "demo",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Inbox" },
    actions: [
      { kind: "click", role: "button", name: "Time — newest first" },
      { kind: "wait", milliseconds: 300 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["inbox"],
  },
  {
    scenarioId: "inbox-markdown",
    route: "/inbox",
    fixtureProfile: "inbox-markdown",
    state: "hover",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Inbox" },
    actions: [
      { kind: "wait", milliseconds: 300 },
      { kind: "hover-css", selector: "a.session-signature" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: [...ids["inbox"], ...ids["global-css"]],
  },
  {
    scenarioId: "inbox-dead-origin",
    route: "/inbox",
    fixtureProfile: "inbox-dead",
    state: "disabled",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Inbox" },
    actions: [
      { kind: "wait", milliseconds: 300 },
      {
        kind: "click",
        role: "button",
        name: "The NVDA quant snapshot is ready.",
        exact: false,
      },
      { kind: "wait", milliseconds: 200 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["inbox"],
  },
  {
    scenarioId: "inbox-reply-reconstructed",
    route: "/inbox",
    fixtureProfile: "inbox-reply-reconstructed",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Inbox" },
    actions: [{ kind: "wait", milliseconds: 500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["inbox"],
  },
  {
    scenarioId: "portfolio-cached",
    route: "/portfolio",
    fixtureProfile: "portfolio-cached",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Portfolio" },
    actions: [{ kind: "wait", milliseconds: 300 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["portfolio"],
  },
  {
    scenarioId: "portfolio-health-degraded",
    route: "/portfolio",
    fixtureProfile: "portfolio-health-degraded",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Portfolio" },
    actions: [{ kind: "wait", milliseconds: 300 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["portfolio"],
  },
  {
    scenarioId: "portfolio",
    route: "/portfolio",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Portfolio" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["portfolio"],
  },
  {
    scenarioId: "portfolio-snapshots-enabled",
    route: "/portfolio",
    fixtureProfile: "demo",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Portfolio" },
    actions: [
      { kind: "click", role: "switch", name: "Enable portfolio snapshots" },
      { kind: "wait", milliseconds: 200 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["portfolio"],
  },
  {
    scenarioId: "portfolio-degraded-snapshot",
    route: "/portfolio",
    fixtureProfile: "snapshot-degraded",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Portfolio" },
    actions: [
      { kind: "wait", milliseconds: 500 },
      { kind: "hover-css", selector: ".recharts-wrapper" },
      { kind: "click-css", selector: ".recharts-wrapper", text: "" },
      { kind: "wait", milliseconds: 500 },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["portfolio"],
  },
  {
    scenarioId: "trading-settings",
    route: "/settings/trading",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Trading" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["trading-settings"],
  },
  {
    scenarioId: "trading-degraded",
    route: "/settings/trading",
    fixtureProfile: "trading-degraded",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Trading" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["trading-settings"],
  },
  {
    scenarioId: "trading-missing-broker-pack",
    route: "/settings/trading",
    fixtureProfile: "broker-pack-missing",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Trading" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["trading-settings"],
  },
  {
    scenarioId: "create-uta-dialog",
    route: "/settings/trading",
    fixtureProfile: "broker-picker",
    state: "dialog-overlay",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connect Broker · Pick Platform" },
    actions: [{ kind: "click", role: "button", name: "+ Add UTA" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["create-uta-dialog"],
  },
  {
    scenarioId: "create-uta-selected",
    route: "/settings/trading",
    fixtureProfile: "broker-picker",
    state: "selected",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Connect Broker · Pick Platform" },
    actions: [
      { kind: "click", role: "button", name: "+ Add UTA" },
      {
        kind: "click",
        role: "button",
        name: "Interactive Brokers",
        exact: false,
      },
      { kind: "click", role: "button", name: "← Back" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["create-uta-dialog"],
  },
  {
    scenarioId: "create-uta-install-pack",
    route: "/settings/trading",
    fixtureProfile: "broker-pack-missing",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: {
      role: "heading",
      name: "Connect Broker · Install Interactive Brokers",
    },
    actions: [
      { kind: "click", role: "button", name: "+ Add UTA" },
      {
        kind: "click",
        role: "button",
        name: "Interactive Brokers",
        exact: false,
      },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["create-uta-dialog"],
  },
  {
    scenarioId: "create-uta-conflict",
    route: "/settings/trading",
    fixtureProfile: "broker-conflict",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: {
      role: "heading",
      name: "Connect Broker · Test Interactive Brokers",
    },
    actions: [
      { kind: "click", role: "button", name: "+ Add UTA" },
      {
        kind: "click",
        role: "button",
        name: "Interactive Brokers",
        exact: false,
      },
      { kind: "click", role: "button", name: "Test Connection →" },
      { kind: "click", role: "button", name: "Save connector" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["create-uta-dialog"],
  },
  {
    scenarioId: "uta-detail",
    route: "/settings/uta/demo-ibkr",
    fixtureProfile: "demo",
    state: "dialog-overlay",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Place Order" },
    actions: [{ kind: "click", role: "button", name: "+ Place Order" }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["uta-detail"],
  },
  {
    scenarioId: "uta-detail-subaccounts",
    route: "/settings/uta/demo-crypto",
    fixtureProfile: "demo",
    state: "selected",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "main" },
    actions: [{ kind: "wait", milliseconds: 500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["uta-detail"],
  },
  {
    scenarioId: "uta-order-partial",
    route: "/settings/uta/demo-ibkr",
    fixtureProfile: "order-partial",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Place Order" },
    actions: [
      { kind: "click", role: "button", name: "+ Place Order" },
      {
        kind: "fill",
        placeholder: "okx-test|BTC/USDT",
        value: "demo-ibkr|AAPL",
      },
      { kind: "fill", placeholder: "0.001", value: "1" },
      {
        kind: "fill",
        placeholder: "Why are you placing this order?",
        value: "audit partial result",
      },
      { kind: "click", role: "button", name: "Place Order" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["uta-detail"],
  },
  {
    scenarioId: "agent-permissions",
    route: "/settings/agent-permissions",
    fixtureProfile: "agent-permissions-warning",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Agent Permissions" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["agent-permissions"],
  },
  {
    scenarioId: "simulator",
    route: "/dev/simulator",
    fixtureProfile: "simulator-audit",
    state: "normal",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Simulator" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["simulator"],
  },
  {
    scenarioId: "simulator-deposit-draft-error",
    route: "/dev/simulator",
    fixtureProfile: "simulator-audit",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Simulator" },
    actions: [
      { kind: "click", role: "tab", name: "External Deposit", exact: false },
      { kind: "select", index: 0, value: "OPT" },
      { kind: "fill", placeholder: "symbol", value: "AAPL" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["simulator"],
  },
  {
    scenarioId: "simulator-trade-draft-error",
    route: "/dev/simulator",
    fixtureProfile: "simulator-audit",
    state: "warning",
    stateDriver: "action",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Simulator" },
    actions: [
      { kind: "click", role: "tab", name: "External Trade", exact: false },
      { kind: "select", index: 0, value: "OPT" },
      { kind: "fill", placeholder: "symbol", value: "AAPL" },
    ],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["simulator"],
  },
  {
    scenarioId: "snapshot-degraded",
    route: "/dev/snapshots",
    fixtureProfile: "snapshot-degraded",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Snapshots" },
    actions: [{ kind: "wait", milliseconds: 500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["global-css"],
  },
  {
    scenarioId: "design-project",
    route: "/design/first-run-onboarding",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "First-run onboarding" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["onboarding-design"],
  },
  {
    scenarioId: "onboarding-design",
    route: "/dev/onboarding",
    fixtureProfile: "demo",
    state: "normal",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Onboarding" },
    actions: [],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["onboarding-design"],
  },
  {
    scenarioId: "onboarding-design-incomplete",
    route: "/dev/onboarding",
    fixtureProfile: "first-run-incomplete",
    state: "warning",
    stateDriver: "fixture",
    themes,
    viewport: desktop,
    ready: { role: "heading", name: "Onboarding" },
    actions: [{ kind: "wait", milliseconds: 500 }],
    expectedSurface: "dom-or-css",
    inventoryIds: ids["onboarding-design"],
  },
  ...[
    ["visual-settings-general", "/settings"],
    ["visual-settings-issues", "/settings/issues"],
    ["visual-settings-mcp", "/settings/mcp"],
    ["visual-settings-market-data", "/settings/market-data"],
    ["visual-settings-news-collector", "/settings/news-collector"],
    ["visual-news", "/news"],
    ["visual-tracked", "/tracked"],
    ["visual-tracked-detail", "/tracked/issues/demo-ws-auto-quant/morning-scan"],
    ["visual-dev-logs", "/dev/logs"],
    ["visual-market-generic", "/market/crypto/BTC-USD"],
    ["visual-independent-harness", "/?visualCoverageHarness=1"],
    ["visual-desktop-update", "/settings?updatePrompt=1"],
    ["visual-update-banner", "/settings?updateBanner=1"],
    ["visual-tab-strip", "/settings"],
    ["visual-template-catalog", "/workspaces/templates"],
    ["visual-template-detail", "/workspaces/templates/chat"],
  ].map(([scenarioId, route]) => ({
    scenarioId: scenarioId!, route: route!, fixtureProfile: "demo", state: "normal",
    themes, viewport: desktop, ready: { role: "main" as const }, actions: [],
    expectedSurface: "dom-or-css" as const, inventoryIds: [] as string[],
  })),
] as const satisfies readonly ThemeColorScenario[];

export const themeColorScenarios: readonly ThemeColorScenario[] = allThemeColorScenarios.filter((scenario) => scenario.inventoryIds.length > 0)
export const themeVisualScenarios: readonly ThemeColorScenario[] = allThemeColorScenarios
